### ISSUE TITLE
about config in per_sample_gradient_clip

### ISSUE THREAD

**Issue by feiyueternal** [woodyx218/opacus_global_clipping#1]
Hi, my code reports a bug when I use **optimizer.virtual_step()** it says module 'config' has no attribute 'Z'. I dont know how to do, help me please!!

**Comment by woodyx218** [comment]
You need to import config library and set config.Z=something in your code. 
E.g. https://github.com/woodyx218/opacus_global_clipping/blob/master/examples/mnist.py. 
This is a step to set global environment.
